Repository NUARIG/competitions, pull requests merged in 2020-11, with the labels that each got.

#671 Add review comments to Excel export #668
  app/views/grants/reviews/index.xlsx.axlsx
Labels: excel/pdf, reviews

#680 Standardize search and action links
  app/assets/stylesheets/app.scss
  app/controllers/grant_permissions_controller.rb
  app/helpers/grant_permissions_helper.rb
  app/views/grant_permissions/_new_form.html.haml
  app/views/grant_permissions/index.html.haml
  app/views/grant_permissions/new.html.haml
  app/views/grant_reviewers/index.html.haml
  app/views/grant_submissions/submissions/index.html.haml
  app/views/grants/reviews/index.html.haml
  app/views/panels/edit.html.haml
  config/locales/activerecord/grant_permission.yml
  spec/system/grant_permissions/grant_permissions_spec.rb
  spec/system/grant_submissions/grant_submission_submissions_spec.rb
  spec/system/panels/panels_spec.rb
Labels: frontend

#678 Use configured application_name on footer and home page #675
  app/views/home/index.html.haml
  app/views/layouts/_footer.html.haml
Labels: frontend, open-source

#681 Redesign grant published button
  app/assets/stylesheets/app.scss
  app/controllers/grant_submissions/submissions_controller.rb
  app/controllers/grants/state_controller.rb
  app/views/grant_permissions/edit.html.haml
  app/views/grant_permissions/index.html.haml
  app/views/grant_permissions/new.html.haml
  app/views/grant_reviewers/index.html.haml
  app/views/grant_submissions/forms/edit.html.haml
  app/views/grant_submissions/submissions/edit.html.haml
  app/views/grant_submissions/submissions/index.html.haml
  app/views/grants/_apply_button.html.haml
  app/views/grants/criteria/index.html.haml
  app/views/grants/edit.html.haml
  app/views/grants/reviews/index.html.haml
  app/views/grants/show.html.haml
  app/views/grants/state/_form.html.haml
  app/views/panels/edit.html.haml
  app/views/shared/_grant_header.html.haml
  app/views/shared/_grant_state.html.haml
  config/routes.rb
  spec/system/grant_submissions/grant_submission_submissions_spec.rb
  spec/system/grants/duplicate_spec.rb
  spec/system/grants/state_spec.rb
Labels: frontend

#684 Fix admin delete submissions
  app/controllers/grant_submissions/submissions_controller.rb
  app/models/grant.rb
  app/policies/grant_policy.rb
  app/policies/grant_submission/submission_policy.rb
  app/views/grant_submissions/submissions/_submission_administrator_links.html.haml
  app/views/grant_submissions/submissions/_submission_applicant_links.html.haml
  app/views/grant_submissions/submissions/index.html.haml
  spec/system/grant_submissions/grant_submission_submissions_spec.rb
Labels: bug, submissions

#687 Feature/dropdown admin links
  app/assets/stylesheets/grants.scss
  app/views/grants/_manage_links.html.haml
  app/views/grants/_sortable_table.html.haml
  spec/factories/grant.rb
  spec/system/grants/duplicate_spec.rb
  spec/system/grants/grants_spec.rb
  spec/system/profiles/grants_spec.rb
Labels: frontend

#689 Account for incomplete reviews in excel export #688
  app/controllers/grants/reviews_controller.rb
  app/views/grants/reviews/index.xlsx.axlsx
Labels: bug, excel/pdf

#694 Hotfix/unable log out 690
  app/controllers/saml_sessions_controller.rb
  spec/system/users/saml_users_spec.rb
Labels: hotfix

#695 fix update method in saml_sessions_controller. #690
  app/controllers/saml_sessions_controller.rb
  config/initializers/version.rb
  spec/system/users/saml_users_spec.rb
Labels: hotfix

#700 Add reviewer invitation model
  app/models/grant.rb
  app/models/grant_reviewer.rb
  app/models/grant_reviewer/invitation.rb
  app/models/paper_trail/grant_reviewer_invitation_version.rb
  config/locales/activerecord/grant_reviewer_invitation.yml
  db/migrate/20201117180406_create_reviewer_invitations.rb
  db/schema.rb
  spec/factories/grant_reviewer_invitation.rb
  spec/models/grant_reviewer_invitation_spec.rb
  spec/models/grant_spec.rb
  spec/models/paper_trail/grant_reviewer_invitation_spec.rb
  spec/system/grant_reviewers/grant_reviewer_invitations_spec.rb
  spec/system/grants/duplicate_spec.rb
Labels: feature, reviewers

#707 Task/update draft submission flash messages
  app/controllers/grant_submissions/submissions_controller.rb
  spec/system/grant_submissions/grant_submission_responses_spec.rb
  spec/system/grant_submissions/grant_submission_submissions_spec.rb
Labels: frontend, submissions

#702 Clarify impact requirement/comment through UI #665
  app/assets/stylesheets/criteria.scss
  app/views/grants/criteria/_overall_impact_fields.html.haml
Labels: frontend, reviews

#701 Task/update reviewer assignment email
  app/controllers/grant_submissions/submissions/reviews_controller.rb
  app/views/reviewer_mailer/assignment.html.haml
  spec/mailers/reviewer_mailer_spec.rb
  spec/system/grants/duplicate_spec.rb
Labels: mailers, reviews

#709 Task/prompt and send invitation
  app/controllers/grant_reviewers/invitations_controller.rb
  app/controllers/grant_reviewers_controller.rb
  app/mailers/grant_reviewer_invitation_mailer.rb
  app/models/registered_user.rb
  app/models/user.rb
  app/views/grant_reviewer_invitation_mailer/invite.html.haml
  config/routes.rb
  spec/factories/grant_reviewer_invitation.rb
  spec/mailers/grant_reviewer_invitation_mailer_spec.rb
  spec/requests/grant_reviewer_requests/invitations_spec.rb
Labels: reviewers

#708 Clarify delete confirm dialogs
  app/assets/javascripts/form_builder_survey.js
  app/assets/stylesheets/grant_submission_form.scss
  app/controllers/grant_submissions/forms_controller.rb
  app/views/banners/_form.html.haml
  app/views/grant_permissions/_admin_links.html.haml
  app/views/grant_permissions/index.html.haml
  app/views/grant_submissions/forms/_form.html.haml
  app/views/grants/_form.html.haml
  lib/grant_submission_form_builder.rb
  spec/system/grant_submissions/grant_submission_forms_spec.rb
  spec/system/grant_submissions/grant_submission_multiple_choice_options_spec.rb
Labels: frontend

#685 add select2 autocomplete to grant_permissions. #372
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/assets/javascripts/grant_permissions.js
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/grant_permissions.scss
  app/views/grant_permissions/_new_form.html.haml
  spec/rails_helper.rb
  spec/system/grant_permissions/grant_permissions_spec.rb
Labels: feature
