Repository NUARIG/competitions, pull requests merged in 2022-02, with the labels that each got.

#892 Hotfix/caching error 891
  app/views/documentation/release/index.html.haml
  config/initializers/version.rb
  lib/devise/competitions_failure_app.rb
Labels: hotfix

#893 Hotfix/caching error 891
  app/views/documentation/release/index.html.haml
  config/initializers/version.rb
  lib/devise/competitions_failure_app.rb
Labels: hotfix

#894 Hotfix/login error better code 891
  app/views/documentation/release/index.html.haml
  config/initializers/version.rb
  lib/devise/competitions_failure_app.rb
Labels: hotfix

#895 Hotfix/login error better code 891
  app/views/documentation/release/index.html.haml
  config/initializers/version.rb
  lib/devise/competitions_failure_app.rb
Labels: hotfix

#898 Task/account for logged in users in devise controllers #896
  app/controllers/application_controller.rb
  app/controllers/login_controller.rb
  app/controllers/registered_users/confirmations_controller.rb
  app/controllers/registered_users/registrations_controller.rb
  app/controllers/registered_users/sessions_controller.rb
  app/views/devise/menu/_login_items.html.haml
  app/views/devise/registrations/edit.html.haml
  app/views/layouts/_header.html.haml
  app/views/layouts/application.html.haml
  app/views/layouts/pdf.html.haml
  config/routes.rb
  spec/system/login/login_spec.rb
  spec/system/users/registered_users/passwords_spec.rb
Labels: log-in / profile, frontend, users, authentication

#902 Task/truncate long grant names on homepage #880
  app/decorators/grant_decorator.rb
  app/views/home/_card.html.haml
  spec/decorators/grant_decorator_spec.rb
  spec/system/home/home_spec.rb
Labels: frontend

#904 Task/update rails #903
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
Labels: upgrade, rails

#907 Task/display applicant name on review assignment #877
  app/controllers/grant_submissions/submissions_controller.rb
  app/views/grant_reviewers/_reviewers.html.haml
  app/views/grant_reviewers/_unassigned_submissions.html.haml
  spec/system/grant_submissions/grant_submission_reviews_spec.rb
Labels: reviews, reviewers, applicants
